require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

deployment_target = '13.0'

platform :ios, deployment_target

production = ENV["PRODUCTION"] == "1"

use_frameworks! :linkage => :static

target 'RNHelloDoctorExampleApp' do
  config = use_native_modules!
  
  use_react_native!(
      :path => config[:reactNativePath],
      # to enable hermes on iOS, change `false` to `true` and then install pods
      :hermes_enabled => false
    )

    pod 'FirebaseAuth'
    pod 'FirebaseFirestore'
    pod 'FirebaseMessaging'

    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
    pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec', :modular_headers => false
  
    target 'RNHelloDoctorExampleAppTests' do
      inherit! :complete
      # Pods for testing
    end

    post_install do |installer|
      react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
    end
end
